version: "3.1"

services:

 db:
  restart: always
  #replicas: 1
  image: postgres:9.3-alpine
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: postgres

  
  #networks:
   # - djangodb 
  #ports: 
  #  - "5432"
  volumes:
    - pg_data:/var/lib/postgresql
 web:
  restart: always
  depends_on:
     - db
  image: kenlavoie/djangobase
  #replicas: 1
  #entrypoint: docker-entrypoint.sh
  command: bash -c "./docker-entrypoint.sh python3 manage.py runserver 0.0.0.0:8000"
  environment:
    DB_NAME: db 
    DB_USER: postgres
    DB_PASSWORD: postgres
    DB_SERVICE: postgres
    DB_PORT: 5432 
    DB_HOST: db:5432
  ports:
    - "8000"
  
  links: 
    - db

  #networks:
  #  - djangofront
  #  - djangodb

 #redis:
  #restart: always
  #image: redis
  #links:
  #   - web

volumes:
    pg_data:
    
#networks:
 # djangofront:
  #  external: true

  #djangodb:
   # external: false
